name: .NET Build

on:
  push:
    branches:
      - staging
  pull_request:
    branches:
      - staging

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Restore Workloads
      run: dotnet workload restore [./MobWxUI.csproj::TargetFramework=net8.0-windows10.0.19041.0]
      working-directory: ./MobWxUI

    - name: Publish with .NET
      run: dotnet publish -f net8.0-windows10.0.19041.0 -c Release -p:RuntimeIdentifierOverride=win10-x64 --no-restore --artifacts-path ./publish
      working-directory: ./MobWxUI

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: publish-output
        path: ./publish
